add_library(mockturtle_abcesop STATIC exor.cpp exorBits.cpp exorCubes.cpp exorLink.cpp exorList.cpp exorUtil.cpp)
set_property(TARGET mockturtle_abcesop PROPERTY EXPORT_NAME abcesop)
target_include_directories(mockturtle_abcesop PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(mockturtle_abcesop PUBLIC mockturtle_abc_platform)
mockturtle_configure_archive(mockturtle_abcesop)
