/* kitty: C++ truth table library
 * Copyright (C) 2017-2022  EPFL
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/*!
  \file shift.hpp
  \brief Shift helper functions

  \author Mathias Soeken
*/

/*! \cond PRIVATE */
#pragma once

#include <cassert>
#include <cstdint>

namespace kitty
{
namespace detail
{

// This code has been auto-generated by Nikolaj Bjorner
// https://github.com/NikolajBjorner/z3/blob/17a256eca1a375f023bb98c3e4e728845d92dfb2/src/ast/expr_network.cpp#L22
inline uint64_t compute_shift( uint64_t x, unsigned code )
{
  switch ( code )
  {
#define x0 ( x & 1 )
#define x1 x0
  case 1:
    return x1;
#define x2 ( x1 | ( x1 << 1 ) )
  case 2:
    return x2;
#define x3 ( x & 3 )
#define x4 x3
  case 3:
    return x4;
#define x5 ( x2 | ( x2 << 2 ) )
  case 4:
    return x5;
#define x6 ( x4 | ( x4 << 2 ) )
  case 5:
    return x6;
#define x7 ( x & 2 )
#define x8 ( x7 << 1 )
#define x9 ( x8 | ( x8 << 1 ) )
#define x10 ( x2 | x9 )
  case 6:
    return x10;
#define x11 ( x & 15 )
#define x12 x11
  case 7:
    return x12;
#define x13 ( x5 | ( x5 << 4 ) )
  case 8:
    return x13;
#define x14 ( x6 | ( x6 << 4 ) )
  case 9:
    return x14;
#define x15 ( x10 | ( x10 << 4 ) )
  case 10:
    return x15;
#define x16 ( x12 | ( x12 << 4 ) )
  case 11:
    return x16;
#define x17 ( x7 << 3 )
#define x18 ( x17 | ( x17 << 1 ) )
#define x19 ( x18 | ( x18 << 2 ) )
#define x20 ( x5 | x19 )
  case 12:
    return x20;
#define x21 ( x & 12 )
#define x22 ( x21 << 2 )
#define x23 ( x22 | ( x22 << 2 ) )
#define x24 ( x6 | x23 )
  case 13:
    return x24;
#define x25 ( x & 4 )
#define x26 ( x25 << 2 )
#define x27 ( x26 | ( x26 << 1 ) )
#define x28 ( x & 8 )
#define x29 ( x28 << 3 )
#define x30 ( x29 | ( x29 << 1 ) )
#define x31 ( x27 | x30 )
#define x32 ( x10 | x31 )
  case 14:
    return x32;
#define x33 ( x & 255 )
#define x34 x33
  case 15:
    return x34;
#define x35 ( x13 | ( x13 << 8 ) )
  case 16:
    return x35;
#define x36 ( x14 | ( x14 << 8 ) )
  case 17:
    return x36;
#define x37 ( x15 | ( x15 << 8 ) )
  case 18:
    return x37;
#define x38 ( x16 | ( x16 << 8 ) )
  case 19:
    return x38;
#define x39 ( x20 | ( x20 << 8 ) )
  case 20:
    return x39;
#define x40 ( x24 | ( x24 << 8 ) )
  case 21:
    return x40;
#define x41 ( x32 | ( x32 << 8 ) )
  case 22:
    return x41;
#define x42 ( x34 | ( x34 << 8 ) )
  case 23:
    return x42;
#define x43 ( x7 << 7 )
#define x44 ( x43 | ( x43 << 1 ) )
#define x45 ( x44 | ( x44 << 2 ) )
#define x46 ( x45 | ( x45 << 4 ) )
#define x47 ( x13 | x46 )
  case 24:
    return x47;
#define x48 ( x21 << 6 )
#define x49 ( x48 | ( x48 << 2 ) )
#define x50 ( x49 | ( x49 << 4 ) )
#define x51 ( x14 | x50 )
  case 25:
    return x51;
#define x52 ( x25 << 6 )
#define x53 ( x52 | ( x52 << 1 ) )
#define x54 ( x28 << 7 )
#define x55 ( x54 | ( x54 << 1 ) )
#define x56 ( x53 | x55 )
#define x57 ( x56 | ( x56 << 4 ) )
#define x58 ( x15 | x57 )
  case 26:
    return x58;
#define x59 ( x & 240 )
#define x60 ( x59 << 4 )
#define x61 ( x60 | ( x60 << 4 ) )
#define x62 ( x16 | x61 )
  case 27:
    return x62;
#define x63 ( x53 | ( x53 << 2 ) )
#define x64 ( x28 << 9 )
#define x65 ( x64 | ( x64 << 1 ) )
#define x66 ( x65 | ( x65 << 2 ) )
#define x67 ( x63 | x66 )
#define x68 ( x20 | x67 )
  case 28:
    return x68;
#define x69 ( x & 48 )
#define x70 ( x69 << 4 )
#define x71 ( x70 | ( x70 << 2 ) )
#define x72 ( x & 192 )
#define x73 ( x72 << 6 )
#define x74 ( x73 | ( x73 << 2 ) )
#define x75 ( x71 | x74 )
#define x76 ( x24 | x75 )
  case 29:
    return x76;
#define x77 ( x & 16 )
#define x78 ( x77 << 4 )
#define x79 ( x78 | ( x78 << 1 ) )
#define x80 ( x & 32 )
#define x81 ( x80 << 5 )
#define x82 ( x81 | ( x81 << 1 ) )
#define x83 ( x79 | x82 )
#define x84 ( x & 64 )
#define x85 ( x84 << 6 )
#define x86 ( x85 | ( x85 << 1 ) )
#define x87 ( x & 128 )
#define x88 ( x87 << 7 )
#define x89 ( x88 | ( x88 << 1 ) )
#define x90 ( x86 | x89 )
#define x91 ( x83 | x90 )
#define x92 ( x32 | x91 )
  case 30:
    return x92;
#define x93 ( x & 65535 )
#define x94 x93
  case 31:
    return x94;
#define x95 ( x35 | ( x35 << 16 ) )
  case 32:
    return x95;
#define x96 ( x36 | ( x36 << 16 ) )
  case 33:
    return x96;
#define x97 ( x37 | ( x37 << 16 ) )
  case 34:
    return x97;
#define x98 ( x38 | ( x38 << 16 ) )
  case 35:
    return x98;
#define x99 ( x39 | ( x39 << 16 ) )
  case 36:
    return x99;
#define x100 ( x40 | ( x40 << 16 ) )
  case 37:
    return x100;
#define x101 ( x41 | ( x41 << 16 ) )
  case 38:
    return x101;
#define x102 ( x42 | ( x42 << 16 ) )
  case 39:
    return x102;
#define x103 ( x47 | ( x47 << 16 ) )
  case 40:
    return x103;
#define x104 ( x51 | ( x51 << 16 ) )
  case 41:
    return x104;
#define x105 ( x58 | ( x58 << 16 ) )
  case 42:
    return x105;
#define x106 ( x62 | ( x62 << 16 ) )
  case 43:
    return x106;
#define x107 ( x68 | ( x68 << 16 ) )
  case 44:
    return x107;
#define x108 ( x76 | ( x76 << 16 ) )
  case 45:
    return x108;
#define x109 ( x92 | ( x92 << 16 ) )
  case 46:
    return x109;
#define x110 ( x94 | ( x94 << 16 ) )
  case 47:
    return x110;
#define x111 ( x7 << 15 )
#define x112 ( x111 | ( x111 << 1 ) )
#define x113 ( x112 | ( x112 << 2 ) )
#define x114 ( x113 | ( x113 << 4 ) )
#define x115 ( x114 | ( x114 << 8 ) )
#define x116 ( x35 | x115 )
  case 48:
    return x116;
#define x117 ( x21 << 14 )
#define x118 ( x117 | ( x117 << 2 ) )
#define x119 ( x118 | ( x118 << 4 ) )
#define x120 ( x119 | ( x119 << 8 ) )
#define x121 ( x36 | x120 )
  case 49:
    return x121;
#define x122 ( x25 << 14 )
#define x123 ( x122 | ( x122 << 1 ) )
#define x124 ( x28 << 15 )
#define x125 ( x124 | ( x124 << 1 ) )
#define x126 ( x123 | x125 )
#define x127 ( x126 | ( x126 << 4 ) )
#define x128 ( x127 | ( x127 << 8 ) )
#define x129 ( x37 | x128 )
  case 50:
    return x129;
#define x130 ( x59 << 12 )
#define x131 ( x130 | ( x130 << 4 ) )
#define x132 ( x131 | ( x131 << 8 ) )
#define x133 ( x38 | x132 )
  case 51:
    return x133;
#define x134 ( x123 | ( x123 << 2 ) )
#define x135 ( x28 << 17 )
#define x136 ( x135 | ( x135 << 1 ) )
#define x137 ( x136 | ( x136 << 2 ) )
#define x138 ( x134 | x137 )
#define x139 ( x138 | ( x138 << 8 ) )
#define x140 ( x39 | x139 )
  case 52:
    return x140;
#define x141 ( x69 << 12 )
#define x142 ( x141 | ( x141 << 2 ) )
#define x143 ( x72 << 14 )
#define x144 ( x143 | ( x143 << 2 ) )
#define x145 ( x142 | x144 )
#define x146 ( x145 | ( x145 << 8 ) )
#define x147 ( x40 | x146 )
  case 53:
    return x147;
#define x148 ( x77 << 12 )
#define x149 ( x148 | ( x148 << 1 ) )
#define x150 ( x80 << 13 )
#define x151 ( x150 | ( x150 << 1 ) )
#define x152 ( x149 | x151 )
#define x153 ( x84 << 14 )
#define x154 ( x153 | ( x153 << 1 ) )
#define x155 ( x87 << 15 )
#define x156 ( x155 | ( x155 << 1 ) )
#define x157 ( x154 | x156 )
#define x158 ( x152 | x157 )
#define x159 ( x158 | ( x158 << 8 ) )
#define x160 ( x41 | x159 )
  case 54:
    return x160;
#define x161 ( x & 65280 )
#define x162 ( x161 << 8 )
#define x163 ( x162 | ( x162 << 8 ) )
#define x164 ( x42 | x163 )
  case 55:
    return x164;
#define x165 ( x134 | ( x134 << 4 ) )
#define x166 ( x28 << 21 )
#define x167 ( x166 | ( x166 << 1 ) )
#define x168 ( x167 | ( x167 << 2 ) )
#define x169 ( x168 | ( x168 << 4 ) )
#define x170 ( x165 | x169 )
#define x171 ( x47 | x170 )
  case 56:
    return x171;
#define x172 ( x142 | ( x142 << 4 ) )
#define x173 ( x72 << 18 )
#define x174 ( x173 | ( x173 << 2 ) )
#define x175 ( x174 | ( x174 << 4 ) )
#define x176 ( x172 | x175 )
#define x177 ( x51 | x176 )
  case 57:
    return x177;
#define x178 ( x152 | ( x152 << 4 ) )
#define x179 ( x84 << 18 )
#define x180 ( x179 | ( x179 << 1 ) )
#define x181 ( x87 << 19 )
#define x182 ( x181 | ( x181 << 1 ) )
#define x183 ( x180 | x182 )
#define x184 ( x183 | ( x183 << 4 ) )
#define x185 ( x178 | x184 )
#define x186 ( x58 | x185 )
  case 58:
    return x186;
#define x187 ( x & 3840 )
#define x188 ( x187 << 8 )
#define x189 ( x188 | ( x188 << 4 ) )
#define x190 ( x & 61440 )
#define x191 ( x190 << 12 )
#define x192 ( x191 | ( x191 << 4 ) )
#define x193 ( x189 | x192 )
#define x194 ( x62 | x193 )
  case 59:
    return x194;
#define x195 ( x149 | ( x149 << 2 ) )
#define x196 ( x80 << 15 )
#define x197 ( x196 | ( x196 << 1 ) )
#define x198 ( x197 | ( x197 << 2 ) )
#define x199 ( x195 | x198 )
#define x200 ( x180 | ( x180 << 2 ) )
#define x201 ( x87 << 21 )
#define x202 ( x201 | ( x201 << 1 ) )
#define x203 ( x202 | ( x202 << 2 ) )
#define x204 ( x200 | x203 )
#define x205 ( x199 | x204 )
#define x206 ( x68 | x205 )
  case 60:
    return x206;
#define x207 ( x & 768 )
#define x208 ( x207 << 8 )
#define x209 ( x208 | ( x208 << 2 ) )
#define x210 ( x & 3072 )
#define x211 ( x210 << 10 )
#define x212 ( x211 | ( x211 << 2 ) )
#define x213 ( x209 | x212 )
#define x214 ( x & 12288 )
#define x215 ( x214 << 12 )
#define x216 ( x215 | ( x215 << 2 ) )
#define x217 ( x & 49152 )
#define x218 ( x217 << 14 )
#define x219 ( x218 | ( x218 << 2 ) )
#define x220 ( x216 | x219 )
#define x221 ( x213 | x220 )
#define x222 ( x76 | x221 )
  case 61:
    return x222;
#define x223 ( x & 256 )
#define x224 ( x223 << 8 )
#define x225 ( x224 | ( x224 << 1 ) )
#define x226 ( x & 512 )
#define x227 ( x226 << 9 )
#define x228 ( x227 | ( x227 << 1 ) )
#define x229 ( x225 | x228 )
#define x230 ( x & 1024 )
#define x231 ( x230 << 10 )
#define x232 ( x231 | ( x231 << 1 ) )
#define x233 ( x & 2048 )
#define x234 ( x233 << 11 )
#define x235 ( x234 | ( x234 << 1 ) )
#define x236 ( x232 | x235 )
#define x237 ( x229 | x236 )
#define x238 ( x & 4096 )
#define x239 ( x238 << 12 )
#define x240 ( x239 | ( x239 << 1 ) )
#define x241 ( x & 8192 )
#define x242 ( x241 << 13 )
#define x243 ( x242 | ( x242 << 1 ) )
#define x244 ( x240 | x243 )
#define x245 ( x & 16384 )
#define x246 ( x245 << 14 )
#define x247 ( x246 | ( x246 << 1 ) )
#define x248 ( x & 32768 )
#define x249 ( x248 << 15 )
#define x250 ( x249 | ( x249 << 1 ) )
#define x251 ( x247 | x250 )
#define x252 ( x244 | x251 )
#define x253 ( x237 | x252 )
#define x254 ( x92 | x253 )
  case 62:
    return x254;
#define x255 ( x & 4294967295 )
#define x256 x255
  case 63:
    return x256;
#define x257 ( x95 | ( x95 << 32 ) )
  case 64:
    return x257;
#define x258 ( x96 | ( x96 << 32 ) )
  case 65:
    return x258;
#define x259 ( x97 | ( x97 << 32 ) )
  case 66:
    return x259;
#define x260 ( x98 | ( x98 << 32 ) )
  case 67:
    return x260;
#define x261 ( x99 | ( x99 << 32 ) )
  case 68:
    return x261;
#define x262 ( x100 | ( x100 << 32 ) )
  case 69:
    return x262;
#define x263 ( x101 | ( x101 << 32 ) )
  case 70:
    return x263;
#define x264 ( x102 | ( x102 << 32 ) )
  case 71:
    return x264;
#define x265 ( x103 | ( x103 << 32 ) )
  case 72:
    return x265;
#define x266 ( x104 | ( x104 << 32 ) )
  case 73:
    return x266;
#define x267 ( x105 | ( x105 << 32 ) )
  case 74:
    return x267;
#define x268 ( x106 | ( x106 << 32 ) )
  case 75:
    return x268;
#define x269 ( x107 | ( x107 << 32 ) )
  case 76:
    return x269;
#define x270 ( x108 | ( x108 << 32 ) )
  case 77:
    return x270;
#define x271 ( x109 | ( x109 << 32 ) )
  case 78:
    return x271;
#define x272 ( x110 | ( x110 << 32 ) )
  case 79:
    return x272;
#define x273 ( x116 | ( x116 << 32 ) )
  case 80:
    return x273;
#define x274 ( x121 | ( x121 << 32 ) )
  case 81:
    return x274;
#define x275 ( x129 | ( x129 << 32 ) )
  case 82:
    return x275;
#define x276 ( x133 | ( x133 << 32 ) )
  case 83:
    return x276;
#define x277 ( x140 | ( x140 << 32 ) )
  case 84:
    return x277;
#define x278 ( x147 | ( x147 << 32 ) )
  case 85:
    return x278;
#define x279 ( x160 | ( x160 << 32 ) )
  case 86:
    return x279;
#define x280 ( x164 | ( x164 << 32 ) )
  case 87:
    return x280;
#define x281 ( x171 | ( x171 << 32 ) )
  case 88:
    return x281;
#define x282 ( x177 | ( x177 << 32 ) )
  case 89:
    return x282;
#define x283 ( x186 | ( x186 << 32 ) )
  case 90:
    return x283;
#define x284 ( x194 | ( x194 << 32 ) )
  case 91:
    return x284;
#define x285 ( x206 | ( x206 << 32 ) )
  case 92:
    return x285;
#define x286 ( x222 | ( x222 << 32 ) )
  case 93:
    return x286;
#define x287 ( x254 | ( x254 << 32 ) )
  case 94:
    return x287;
#define x288 ( x256 | ( x256 << 32 ) )
  case 95:
    return x288;
#define x289 ( x7 << 31 )
#define x290 ( x289 | ( x289 << 1 ) )
#define x291 ( x290 | ( x290 << 2 ) )
#define x292 ( x291 | ( x291 << 4 ) )
#define x293 ( x292 | ( x292 << 8 ) )
#define x294 ( x293 | ( x293 << 16 ) )
#define x295 ( x95 | x294 )
  case 96:
    return x295;
#define x296 ( x21 << 30 )
#define x297 ( x296 | ( x296 << 2 ) )
#define x298 ( x297 | ( x297 << 4 ) )
#define x299 ( x298 | ( x298 << 8 ) )
#define x300 ( x299 | ( x299 << 16 ) )
#define x301 ( x96 | x300 )
  case 97:
    return x301;
#define x302 ( x25 << 30 )
#define x303 ( x302 | ( x302 << 1 ) )
#define x304 ( x28 << 31 )
#define x305 ( x304 | ( x304 << 1 ) )
#define x306 ( x303 | x305 )
#define x307 ( x306 | ( x306 << 4 ) )
#define x308 ( x307 | ( x307 << 8 ) )
#define x309 ( x308 | ( x308 << 16 ) )
#define x310 ( x97 | x309 )
  case 98:
    return x310;
#define x311 ( x59 << 28 )
#define x312 ( x311 | ( x311 << 4 ) )
#define x313 ( x312 | ( x312 << 8 ) )
#define x314 ( x313 | ( x313 << 16 ) )
#define x315 ( x98 | x314 )
  case 99:
    return x315;
#define x316 ( x303 | ( x303 << 2 ) )
#define x317 ( x28 << 33 )
#define x318 ( x317 | ( x317 << 1 ) )
#define x319 ( x318 | ( x318 << 2 ) )
#define x320 ( x316 | x319 )
#define x321 ( x320 | ( x320 << 8 ) )
#define x322 ( x321 | ( x321 << 16 ) )
#define x323 ( x99 | x322 )
  case 100:
    return x323;
#define x324 ( x69 << 28 )
#define x325 ( x324 | ( x324 << 2 ) )
#define x326 ( x72 << 30 )
#define x327 ( x326 | ( x326 << 2 ) )
#define x328 ( x325 | x327 )
#define x329 ( x328 | ( x328 << 8 ) )
#define x330 ( x329 | ( x329 << 16 ) )
#define x331 ( x100 | x330 )
  case 101:
    return x331;
#define x332 ( x77 << 28 )
#define x333 ( x332 | ( x332 << 1 ) )
#define x334 ( x80 << 29 )
#define x335 ( x334 | ( x334 << 1 ) )
#define x336 ( x333 | x335 )
#define x337 ( x84 << 30 )
#define x338 ( x337 | ( x337 << 1 ) )
#define x339 ( x87 << 31 )
#define x340 ( x339 | ( x339 << 1 ) )
#define x341 ( x338 | x340 )
#define x342 ( x336 | x341 )
#define x343 ( x342 | ( x342 << 8 ) )
#define x344 ( x343 | ( x343 << 16 ) )
#define x345 ( x101 | x344 )
  case 102:
    return x345;
#define x346 ( x161 << 24 )
#define x347 ( x346 | ( x346 << 8 ) )
#define x348 ( x347 | ( x347 << 16 ) )
#define x349 ( x102 | x348 )
  case 103:
    return x349;
#define x350 ( x316 | ( x316 << 4 ) )
#define x351 ( x28 << 37 )
#define x352 ( x351 | ( x351 << 1 ) )
#define x353 ( x352 | ( x352 << 2 ) )
#define x354 ( x353 | ( x353 << 4 ) )
#define x355 ( x350 | x354 )
#define x356 ( x355 | ( x355 << 16 ) )
#define x357 ( x103 | x356 )
  case 104:
    return x357;
#define x358 ( x325 | ( x325 << 4 ) )
#define x359 ( x72 << 34 )
#define x360 ( x359 | ( x359 << 2 ) )
#define x361 ( x360 | ( x360 << 4 ) )
#define x362 ( x358 | x361 )
#define x363 ( x362 | ( x362 << 16 ) )
#define x364 ( x104 | x363 )
  case 105:
    return x364;
#define x365 ( x336 | ( x336 << 4 ) )
#define x366 ( x84 << 34 )
#define x367 ( x366 | ( x366 << 1 ) )
#define x368 ( x87 << 35 )
#define x369 ( x368 | ( x368 << 1 ) )
#define x370 ( x367 | x369 )
#define x371 ( x370 | ( x370 << 4 ) )
#define x372 ( x365 | x371 )
#define x373 ( x372 | ( x372 << 16 ) )
#define x374 ( x105 | x373 )
  case 106:
    return x374;
#define x375 ( x187 << 24 )
#define x376 ( x375 | ( x375 << 4 ) )
#define x377 ( x190 << 28 )
#define x378 ( x377 | ( x377 << 4 ) )
#define x379 ( x376 | x378 )
#define x380 ( x379 | ( x379 << 16 ) )
#define x381 ( x106 | x380 )
  case 107:
    return x381;
#define x382 ( x333 | ( x333 << 2 ) )
#define x383 ( x80 << 31 )
#define x384 ( x383 | ( x383 << 1 ) )
#define x385 ( x384 | ( x384 << 2 ) )
#define x386 ( x382 | x385 )
#define x387 ( x367 | ( x367 << 2 ) )
#define x388 ( x87 << 37 )
#define x389 ( x388 | ( x388 << 1 ) )
#define x390 ( x389 | ( x389 << 2 ) )
#define x391 ( x387 | x390 )
#define x392 ( x386 | x391 )
#define x393 ( x392 | ( x392 << 16 ) )
#define x394 ( x107 | x393 )
  case 108:
    return x394;
#define x395 ( x207 << 24 )
#define x396 ( x395 | ( x395 << 2 ) )
#define x397 ( x210 << 26 )
#define x398 ( x397 | ( x397 << 2 ) )
#define x399 ( x396 | x398 )
#define x400 ( x214 << 28 )
#define x401 ( x400 | ( x400 << 2 ) )
#define x402 ( x217 << 30 )
#define x403 ( x402 | ( x402 << 2 ) )
#define x404 ( x401 | x403 )
#define x405 ( x399 | x404 )
#define x406 ( x405 | ( x405 << 16 ) )
#define x407 ( x108 | x406 )
  case 109:
    return x407;
#define x408 ( x223 << 24 )
#define x409 ( x408 | ( x408 << 1 ) )
#define x410 ( x226 << 25 )
#define x411 ( x410 | ( x410 << 1 ) )
#define x412 ( x409 | x411 )
#define x413 ( x230 << 26 )
#define x414 ( x413 | ( x413 << 1 ) )
#define x415 ( x233 << 27 )
#define x416 ( x415 | ( x415 << 1 ) )
#define x417 ( x414 | x416 )
#define x418 ( x412 | x417 )
#define x419 ( x238 << 28 )
#define x420 ( x419 | ( x419 << 1 ) )
#define x421 ( x241 << 29 )
#define x422 ( x421 | ( x421 << 1 ) )
#define x423 ( x420 | x422 )
#define x424 ( x245 << 30 )
#define x425 ( x424 | ( x424 << 1 ) )
#define x426 ( x248 << 31 )
#define x427 ( x426 | ( x426 << 1 ) )
#define x428 ( x425 | x427 )
#define x429 ( x423 | x428 )
#define x430 ( x418 | x429 )
#define x431 ( x430 | ( x430 << 16 ) )
#define x432 ( x109 | x431 )
  case 110:
    return x432;
#define x433 ( x & 4294901760 )
#define x434 ( x433 << 16 )
#define x435 ( x434 | ( x434 << 16 ) )
#define x436 ( x110 | x435 )
  case 111:
    return x436;
#define x437 ( x350 | ( x350 << 8 ) )
#define x438 ( x28 << 45 )
#define x439 ( x438 | ( x438 << 1 ) )
#define x440 ( x439 | ( x439 << 2 ) )
#define x441 ( x440 | ( x440 << 4 ) )
#define x442 ( x441 | ( x441 << 8 ) )
#define x443 ( x437 | x442 )
#define x444 ( x116 | x443 )
  case 112:
    return x444;
#define x445 ( x358 | ( x358 << 8 ) )
#define x446 ( x72 << 42 )
#define x447 ( x446 | ( x446 << 2 ) )
#define x448 ( x447 | ( x447 << 4 ) )
#define x449 ( x448 | ( x448 << 8 ) )
#define x450 ( x445 | x449 )
#define x451 ( x121 | x450 )
  case 113:
    return x451;
#define x452 ( x365 | ( x365 << 8 ) )
#define x453 ( x84 << 42 )
#define x454 ( x453 | ( x453 << 1 ) )
#define x455 ( x87 << 43 )
#define x456 ( x455 | ( x455 << 1 ) )
#define x457 ( x454 | x456 )
#define x458 ( x457 | ( x457 << 4 ) )
#define x459 ( x458 | ( x458 << 8 ) )
#define x460 ( x452 | x459 )
#define x461 ( x129 | x460 )
  case 114:
    return x461;
#define x462 ( x376 | ( x376 << 8 ) )
#define x463 ( x190 << 36 )
#define x464 ( x463 | ( x463 << 4 ) )
#define x465 ( x464 | ( x464 << 8 ) )
#define x466 ( x462 | x465 )
#define x467 ( x133 | x466 )
  case 115:
    return x467;
#define x468 ( x386 | ( x386 << 8 ) )
#define x469 ( x454 | ( x454 << 2 ) )
#define x470 ( x87 << 45 )
#define x471 ( x470 | ( x470 << 1 ) )
#define x472 ( x471 | ( x471 << 2 ) )
#define x473 ( x469 | x472 )
#define x474 ( x473 | ( x473 << 8 ) )
#define x475 ( x468 | x474 )
#define x476 ( x140 | x475 )
  case 116:
    return x476;
#define x477 ( x399 | ( x399 << 8 ) )
#define x478 ( x214 << 36 )
#define x479 ( x478 | ( x478 << 2 ) )
#define x480 ( x217 << 38 )
#define x481 ( x480 | ( x480 << 2 ) )
#define x482 ( x479 | x481 )
#define x483 ( x482 | ( x482 << 8 ) )
#define x484 ( x477 | x483 )
#define x485 ( x147 | x484 )
  case 117:
    return x485;
#define x486 ( x418 | ( x418 << 8 ) )
#define x487 ( x238 << 36 )
#define x488 ( x487 | ( x487 << 1 ) )
#define x489 ( x241 << 37 )
#define x490 ( x489 | ( x489 << 1 ) )
#define x491 ( x488 | x490 )
#define x492 ( x245 << 38 )
#define x493 ( x492 | ( x492 << 1 ) )
#define x494 ( x248 << 39 )
#define x495 ( x494 | ( x494 << 1 ) )
#define x496 ( x493 | x495 )
#define x497 ( x491 | x496 )
#define x498 ( x497 | ( x497 << 8 ) )
#define x499 ( x486 | x498 )
#define x500 ( x160 | x499 )
  case 118:
    return x500;
#define x501 ( x & 16711680 )
#define x502 ( x501 << 16 )
#define x503 ( x502 | ( x502 << 8 ) )
#define x504 ( x & 4278190080 )
#define x505 ( x504 << 24 )
#define x506 ( x505 | ( x505 << 8 ) )
#define x507 ( x503 | x506 )
#define x508 ( x164 | x507 )
  case 119:
    return x508;
#define x509 ( x382 | ( x382 << 4 ) )
#define x510 ( x80 << 35 )
#define x511 ( x510 | ( x510 << 1 ) )
#define x512 ( x511 | ( x511 << 2 ) )
#define x513 ( x512 | ( x512 << 4 ) )
#define x514 ( x509 | x513 )
#define x515 ( x469 | ( x469 << 4 ) )
#define x516 ( x87 << 49 )
#define x517 ( x516 | ( x516 << 1 ) )
#define x518 ( x517 | ( x517 << 2 ) )
#define x519 ( x518 | ( x518 << 4 ) )
#define x520 ( x515 | x519 )
#define x521 ( x514 | x520 )
#define x522 ( x171 | x521 )
  case 120:
    return x522;
#define x523 ( x396 | ( x396 << 4 ) )
#define x524 ( x210 << 30 )
#define x525 ( x524 | ( x524 << 2 ) )
#define x526 ( x525 | ( x525 << 4 ) )
#define x527 ( x523 | x526 )
#define x528 ( x479 | ( x479 << 4 ) )
#define x529 ( x217 << 42 )
#define x530 ( x529 | ( x529 << 2 ) )
#define x531 ( x530 | ( x530 << 4 ) )
#define x532 ( x528 | x531 )
#define x533 ( x527 | x532 )
#define x534 ( x177 | x533 )
  case 121:
    return x534;
#define x535 ( x412 | ( x412 << 4 ) )
#define x536 ( x230 << 30 )
#define x537 ( x536 | ( x536 << 1 ) )
#define x538 ( x233 << 31 )
#define x539 ( x538 | ( x538 << 1 ) )
#define x540 ( x537 | x539 )
#define x541 ( x540 | ( x540 << 4 ) )
#define x542 ( x535 | x541 )
#define x543 ( x491 | ( x491 << 4 ) )
#define x544 ( x245 << 42 )
#define x545 ( x544 | ( x544 << 1 ) )
#define x546 ( x248 << 43 )
#define x547 ( x546 | ( x546 << 1 ) )
#define x548 ( x545 | x547 )
#define x549 ( x548 | ( x548 << 4 ) )
#define x550 ( x543 | x549 )
#define x551 ( x542 | x550 )
#define x552 ( x186 | x551 )
  case 122:
    return x552;
#define x553 ( x & 983040 )
#define x554 ( x553 << 16 )
#define x555 ( x554 | ( x554 << 4 ) )
#define x556 ( x & 15728640 )
#define x557 ( x556 << 20 )
#define x558 ( x557 | ( x557 << 4 ) )
#define x559 ( x555 | x558 )
#define x560 ( x & 251658240 )
#define x561 ( x560 << 24 )
#define x562 ( x561 | ( x561 << 4 ) )
#define x563 ( x & 4026531840 )
#define x564 ( x563 << 28 )
#define x565 ( x564 | ( x564 << 4 ) )
#define x566 ( x562 | x565 )
#define x567 ( x559 | x566 )
#define x568 ( x194 | x567 )
  case 123:
    return x568;
#define x569 ( x409 | ( x409 << 2 ) )
#define x570 ( x226 << 27 )
#define x571 ( x570 | ( x570 << 1 ) )
#define x572 ( x571 | ( x571 << 2 ) )
#define x573 ( x569 | x572 )
#define x574 ( x537 | ( x537 << 2 ) )
#define x575 ( x233 << 33 )
#define x576 ( x575 | ( x575 << 1 ) )
#define x577 ( x576 | ( x576 << 2 ) )
#define x578 ( x574 | x577 )
#define x579 ( x573 | x578 )
#define x580 ( x488 | ( x488 << 2 ) )
#define x581 ( x241 << 39 )
#define x582 ( x581 | ( x581 << 1 ) )
#define x583 ( x582 | ( x582 << 2 ) )
#define x584 ( x580 | x583 )
#define x585 ( x545 | ( x545 << 2 ) )
#define x586 ( x248 << 45 )
#define x587 ( x586 | ( x586 << 1 ) )
#define x588 ( x587 | ( x587 << 2 ) )
#define x589 ( x585 | x588 )
#define x590 ( x584 | x589 )
#define x591 ( x579 | x590 )
#define x592 ( x206 | x591 )
  case 124:
    return x592;
#define x593 ( x & 196608 )
#define x594 ( x593 << 16 )
#define x595 ( x594 | ( x594 << 2 ) )
#define x596 ( x & 786432 )
#define x597 ( x596 << 18 )
#define x598 ( x597 | ( x597 << 2 ) )
#define x599 ( x595 | x598 )
#define x600 ( x & 3145728 )
#define x601 ( x600 << 20 )
#define x602 ( x601 | ( x601 << 2 ) )
#define x603 ( x & 12582912 )
#define x604 ( x603 << 22 )
#define x605 ( x604 | ( x604 << 2 ) )
#define x606 ( x602 | x605 )
#define x607 ( x599 | x606 )
#define x608 ( x & 50331648 )
#define x609 ( x608 << 24 )
#define x610 ( x609 | ( x609 << 2 ) )
#define x611 ( x & 201326592 )
#define x612 ( x611 << 26 )
#define x613 ( x612 | ( x612 << 2 ) )
#define x614 ( x610 | x613 )
#define x615 ( x & 805306368 )
#define x616 ( x615 << 28 )
#define x617 ( x616 | ( x616 << 2 ) )
#define x618 ( x & 3221225472 )
#define x619 ( x618 << 30 )
#define x620 ( x619 | ( x619 << 2 ) )
#define x621 ( x617 | x620 )
#define x622 ( x614 | x621 )
#define x623 ( x607 | x622 )
#define x624 ( x222 | x623 )
  case 125:
    return x624;
#define x625 ( x & 65536 )
#define x626 ( x625 << 16 )
#define x627 ( x626 | ( x626 << 1 ) )
#define x628 ( x & 131072 )
#define x629 ( x628 << 17 )
#define x630 ( x629 | ( x629 << 1 ) )
#define x631 ( x627 | x630 )
#define x632 ( x & 262144 )
#define x633 ( x632 << 18 )
#define x634 ( x633 | ( x633 << 1 ) )
#define x635 ( x & 524288 )
#define x636 ( x635 << 19 )
#define x637 ( x636 | ( x636 << 1 ) )
#define x638 ( x634 | x637 )
#define x639 ( x631 | x638 )
#define x640 ( x & 1048576 )
#define x641 ( x640 << 20 )
#define x642 ( x641 | ( x641 << 1 ) )
#define x643 ( x & 2097152 )
#define x644 ( x643 << 21 )
#define x645 ( x644 | ( x644 << 1 ) )
#define x646 ( x642 | x645 )
#define x647 ( x & 4194304 )
#define x648 ( x647 << 22 )
#define x649 ( x648 | ( x648 << 1 ) )
#define x650 ( x & 8388608 )
#define x651 ( x650 << 23 )
#define x652 ( x651 | ( x651 << 1 ) )
#define x653 ( x649 | x652 )
#define x654 ( x646 | x653 )
#define x655 ( x639 | x654 )
#define x656 ( x & 16777216 )
#define x657 ( x656 << 24 )
#define x658 ( x657 | ( x657 << 1 ) )
#define x659 ( x & 33554432 )
#define x660 ( x659 << 25 )
#define x661 ( x660 | ( x660 << 1 ) )
#define x662 ( x658 | x661 )
#define x663 ( x & 67108864 )
#define x664 ( x663 << 26 )
#define x665 ( x664 | ( x664 << 1 ) )
#define x666 ( x & 134217728 )
#define x667 ( x666 << 27 )
#define x668 ( x667 | ( x667 << 1 ) )
#define x669 ( x665 | x668 )
#define x670 ( x662 | x669 )
#define x671 ( x & 268435456 )
#define x672 ( x671 << 28 )
#define x673 ( x672 | ( x672 << 1 ) )
#define x674 ( x & 536870912 )
#define x675 ( x674 << 29 )
#define x676 ( x675 | ( x675 << 1 ) )
#define x677 ( x673 | x676 )
#define x678 ( x & 1073741824 )
#define x679 ( x678 << 30 )
#define x680 ( x679 | ( x679 << 1 ) )
#define x681 ( x & 2147483648 )
#define x682 ( x681 << 31 )
#define x683 ( x682 | ( x682 << 1 ) )
#define x684 ( x680 | x683 )
#define x685 ( x677 | x684 )
#define x686 ( x670 | x685 )
#define x687 ( x655 | x686 )
#define x688 ( x254 | x687 )
  case 126:
    return x688;
  case 127:
    return x;
  default:
    assert( false );
    return 0;
  }
}

} // namespace detail
} // namespace kitty

/*! \endcond */
