add_library(mockturtle INTERFACE)
add_library(mockturtle::mockturtle ALIAS mockturtle)
target_compile_features(mockturtle INTERFACE cxx_std_17)
target_include_directories(mockturtle SYSTEM INTERFACE
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
  $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)
target_link_libraries(mockturtle INTERFACE mockturtle_dependencies)

foreach(component sat esop all)
  add_library(mockturtle_${component} INTERFACE)
  add_library(mockturtle::${component} ALIAS mockturtle_${component})
  set_property(TARGET mockturtle_${component} PROPERTY EXPORT_NAME ${component})
endforeach()
target_link_libraries(mockturtle_sat INTERFACE mockturtle mockturtle_abcsat)
target_link_libraries(mockturtle_esop INTERFACE mockturtle mockturtle_abcesop)
target_link_libraries(mockturtle_all INTERFACE mockturtle_sat mockturtle_esop)
if(MOCKTURTLE_ENABLE_NAUTY)
  target_link_libraries(mockturtle_all INTERFACE mockturtle_nauty)
endif()
if(MOCKTURTLE_ENABLE_ABC)
  target_link_libraries(mockturtle_all INTERFACE MockturtleABC::ABC ${CMAKE_DL_LIBS})
  target_compile_definitions(mockturtle_all INTERFACE MOCKTURTLE_ENABLE_ABC)
endif()
if(BILL_Z3)
  target_link_libraries(mockturtle_all INTERFACE MockturtleZ3::Z3)
  target_compile_definitions(mockturtle_all INTERFACE BILL_HAS_Z3)
endif()
if(MOCKTURTLE_ENABLE_MATPLOTLIB)
  target_link_libraries(mockturtle_all INTERFACE Python3::Python Python3::NumPy)
endif()
if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9)
  target_link_libraries(mockturtle INTERFACE stdc++fs)
endif()
